version: "3.9"
services:
  api:
    build: ./server
    env_file: ./server/.env
    ports: ["3000:3000"]
    depends_on: [mongo, redis]
  mongo:
    image: mongo:7
    ports: ["27017:27017"]
    volumes: ["mongo-data:/data/db"]
  redis:
    image: redis:7
    ports: ["6379:6379"]
volumes:
  mongo-data:
